# Generated by Django 3.1.7 on 2021-05-03 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('engine_power', models.IntegerField()),
                ('gear_case', models.CharField(choices=[('m', 'Mechanic'), ('a', 'Automatic')], max_length=1)),
                ('fuel_type', models.CharField(choices=[('p', 'Petrol'), ('gas', 'Gas'), ('dis', 'Diesel'), ('el', 'Electric'), ('hg', 'Hydrogen')], max_length=3)),
                ('status', models.CharField(choices=[('sol', 'sold'), ('sel', 'selling'), ('arc', 'archived')], max_length=3)),
                ('engine_type', models.CharField(max_length=50)),
                ('population_type', models.CharField(max_length=50)),
                ('doors', models.IntegerField()),
                ('number', models.CharField(max_length=10)),
                ('sitting_place', models.CharField(choices=[('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('more', 'more then five')], max_length=4)),
                ('first_registration_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('metadata', models.CharField(max_length=30)),
                ('url', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Car photo')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=244)),
                ('phone_number', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('sol', 'sold'), ('sel', 'selling'), ('arc', 'archived')], max_length=3, null=True)),
                ('car', models.ForeignKey(on_delete=models.SET('Sold'), to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CarProperty',
            fields=[
                ('car_property', models.IntegerField(primary_key=True, serialize=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.property')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.color'),
        ),
    ]
